AWSTemplateFormatVersion: '2010-09-09'
Description: 'Hard Wordle - FREE TIER ONLY - CI/CD Pipeline for S3 Static Website'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, prod)
    AllowedValues:
      - dev
      - prod
  
  CodeStarConnectionArn:
    Type: String
    Description: ARN of the CodeStar Connection to your Git provider (GitHub, GitLab, or Bitbucket)
  
  RepositoryId:
    Type: String
    Description: Full repository ID in format 'owner/repo-name' (e.g., 'myusername/hard-wordle')
  
  BranchName:
    Type: String
    Default: main
    Description: Git branch to track for automatic deployments

Resources:
  # S3 Bucket for Pipeline Artifacts (Free Tier: 5GB)
  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-hard-wordle-artifacts-${AWS::AccountId}
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldArtifacts
            Status: Enabled
            ExpirationInDays: 7  # Keep for only 7 days to minimize storage
          - Id: DeleteIncompleteMultipartUploads
            Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 1
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-hard-wordle-artifacts
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hard-wordle
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Role for CodeBuild (Free Tier: 100 build minutes/month)
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-hard-wordle-codebuild-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # CloudWatch Logs permissions (Free Tier: 5GB)
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource:
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${EnvironmentName}-hard-wordle-build
                  - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${EnvironmentName}-hard-wordle-build:*
              # S3 permissions for artifacts
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                Resource:
                  - !Sub ${ArtifactBucket.Arn}/*
              # S3 permissions for website bucket
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - Fn::ImportValue: !Sub ${EnvironmentName}-hard-wordle-bucket-name
                  - !Sub 
                    - "${BucketArn}/*"
                    - BucketArn: 
                        Fn::Sub:
                          - "arn:aws:s3:::${BucketName}"
                          - BucketName:
                              Fn::ImportValue: !Sub ${EnvironmentName}-hard-wordle-bucket-name
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-hard-wordle-codebuild-role
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hard-wordle
        - Key: ManagedBy
          Value: CloudFormation

  # IAM Role for CodePipeline (Free Tier: 1 pipeline/month)
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${EnvironmentName}-hard-wordle-codepipeline-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # S3 permissions for artifacts
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:GetBucketLocation
                  - s3:ListBucket
                Resource:
                  - !GetAtt ArtifactBucket.Arn
                  - !Sub ${ArtifactBucket.Arn}/*
              # CodeBuild permissions
              - Effect: Allow
                Action:
                  - codebuild:BatchGetBuilds
                  - codebuild:StartBuild
                Resource:
                  - !GetAtt CodeBuildProject.Arn
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-hard-wordle-codepipeline-role
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hard-wordle
        - Key: ManagedBy
          Value: CloudFormation

  # CodeBuild Project (Free Tier: 100 minutes/month)
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${EnvironmentName}-hard-wordle-build
      Description: Build and deploy Hard Wordle static website
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL  # Smallest instance for free tier
        Image: aws/codebuild/standard:7.0
        PrivilegedMode: false  # Not needed for static site
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: WEBSITE_BUCKET
            Value:
              Fn::ImportValue: !Sub ${EnvironmentName}-hard-wordle-bucket-name
      Source:
        Type: CODEPIPELINE
        BuildSpec: |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 18
            pre_build:
              commands:
                - echo Logging in to Amazon ECR...
                - echo Build started on `date`
                - echo Installing dependencies...
                - npm install
            build:
              commands:
                - echo Build started on `date`
                - echo Running tests...
                - npm test
                - echo Building the application...
                - npm run build
            post_build:
              commands:
                - echo Build completed on `date`
                - echo Deploying to S3...
                - aws s3 sync dist/ s3://$WEBSITE_BUCKET --delete
                - echo Deployment completed
          artifacts:
            files:
              - '**/*'
            base-directory: dist
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: !Sub /aws/codebuild/${EnvironmentName}-hard-wordle-build
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-hard-wordle-build
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hard-wordle
        - Key: ManagedBy
          Value: CloudFormation

  # CodePipeline (Free Tier: 1 active pipeline/month)
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${EnvironmentName}-hard-wordle-pipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        # Source Stage
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeStarSourceConnection
                Version: '1'
              Configuration:
                ConnectionArn: !Ref CodeStarConnectionArn
                FullRepositoryId: !Ref RepositoryId
                BranchName: !Ref BranchName
                OutputArtifactFormat: CODE_ZIP
                DetectChanges: true
              OutputArtifacts:
                - Name: SourceOutput
        
        # Build and Deploy Stage
        - Name: BuildAndDeploy
          Actions:
            - Name: BuildAndDeployAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: SourceOutput
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-hard-wordle-pipeline
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hard-wordle
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  PipelineName:
    Description: CodePipeline Name
    Value: !Ref Pipeline
    Export:
      Name: !Sub ${EnvironmentName}-hard-wordle-pipeline-name

  PipelineUrl:
    Description: CodePipeline URL
    Value: !Sub https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${Pipeline}/view

  CodeBuildProjectName:
    Description: CodeBuild Project Name
    Value: !Ref CodeBuildProject
    Export:
      Name: !Sub ${EnvironmentName}-hard-wordle-codebuild-project

  ArtifactBucketName:
    Description: S3 Bucket for Pipeline Artifacts
    Value: !Ref ArtifactBucket
    Export:
      Name: !Sub ${EnvironmentName}-hard-wordle-artifact-bucket