AWSTemplateFormatVersion: '2010-09-09'
Description: 'Hard Wordle - FREE TIER ONLY - Static S3 Website with CloudFront'

Parameters:
  EnvironmentName:
    Type: String
    Default: dev
    Description: Environment name (dev, prod)
    AllowedValues:
      - dev
      - prod

Resources:
  # S3 Bucket for Static Website Hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${EnvironmentName}-hard-wordle-website-${AWS::AccountId}
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName}-hard-wordle-website
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Project
          Value: hard-wordle
        - Key: ManagedBy
          Value: CloudFormation

  # S3 Bucket Policy for Public Read Access
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub ${WebsiteBucket.Arn}/*

  # CloudWatch Log Group (Free Tier: 5GB)
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/s3/${EnvironmentName}-hard-wordle
      RetentionInDays: 7

Outputs:
  WebsiteURL:
    Description: URL of the S3 Website
    Value: !GetAtt WebsiteBucket.WebsiteURL
    Export:
      Name: !Sub ${EnvironmentName}-hard-wordle-website-url

  BucketName:
    Description: S3 Bucket Name
    Value: !Ref WebsiteBucket
    Export:
      Name: !Sub ${EnvironmentName}-hard-wordle-bucket-name

  WebsiteDomain:
    Description: Website Domain
    Value: !Sub ${WebsiteBucket}.s3-website-${AWS::Region}.amazonaws.com
    Export:
      Name: !Sub ${EnvironmentName}-hard-wordle-domain